name: odoo_repository
description:  Dart package helps to implement data communication between Odoo and dart client with persistance and offline mode
version: 0.1.4
homepage: https://github.com/ERP-Ukraine/odoo-repository-dart
repository: https://github.com/ERP-Ukraine/odoo-repository-dart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  odoo_rpc:
    git:
      url: https://github.com/calvinehm/odoo-rpc-dart.git
      ref: master
  logger: ^1.0.0
  crypto: ^3.0.0
  pedantic: ^1.11.1
